name: Update Org Profile

on:
  schedule:
    - cron: "0 0 1 * *" # every 1st day of the month at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install node-fetch

      - name: Generate README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node scripts/generate-readme.js

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add profile/README.md
          git commit -m "🔄 Auto-update org profile README" || echo "No changes to commit"

      - name: Who am I? (test PAT authentication)
        env:
          TOKEN: ${{ secrets.ORG_README_UPDATE }}
        run: |
          curl -H "Authorization: token ${TOKEN}" https://api.github.com/user

      - name: Push changes
        env:
          TOKEN: ${{ secrets.ORG_README_UPDATE }}
        run: |
          # Disable GitHub Actions bot credential helper
          git config --global --unset credential.helper
          
          # Set remote with PAT explicitly
          git remote set-url origin "https://x-access-token:${TOKEN}@github.com/Kandy-Agency/.github.git"
          
          # Push changes
          git push origin HEAD:main
